services:
  cert-gen:
    image: cert-nss
    profiles: ["manual"]  # exclude from `docker compose up`
    volumes:
      - ./certs:/work/certs
    working_dir: /work/certs
    entrypoint: ["/bin/sh", "-c"]
    command: >
      '
      rm -r -f nssdb &&
      mkdir -p nssdb &&
      openssl req -x509 -newkey rsa:1024 \
        -keyout key.pem \
        -out cert.pem \
        -sha256 -days 365 -nodes \
        -subj "/CN=ras.dev" &&
      cat cert.pem key.pem > server.pem &&
      rm cert.pem key.pem &&
      certutil -N -d nssdb --empty-password &&
      certutil -A -n "RAS" -t "CT,,C" -i server.pem -d nssdb
      '

  retro-aim-server:
    image: ras:main
    ports:
      - "5190:5190"
      - "5191:5191"
      - "5192:5192"
      - "5193:5193"
      - "5194:5194"
      - "5195:5195"
      - "5196:5196"
      - "5197:5197"
      - "8080:8080"
    environment:
      - OSCAR_HOST=ras.dev
    env_file:
      - ./config/settings.env

  stunnel:
    image: stunnel:5.75-openssl-1.0.2u
    ports:
      - "443:443"
    volumes:
      - ./config/ssl/stunnel.conf:/etc/stunnel/stunnel.conf:ro
      - ./certs:/etc/stunnel/certs:ro
    command: stunnel.conf
